apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webapp
  labels:
    app: sample-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-webapp
  template:
    metadata:
      labels:
        app: sample-webapp
    spec:
      containers:
        - name: sample-webapp
          image: your-registry/sample-webapp:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
