apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-flask
  template:
    metadata:
      labels:
        app: sample-flask
    spec:
      containers:
        - name: sample-flask
          image: yashwanth0422/sample-flask:21a038ae657a0f17c7a771087cb02acb46e10786
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10   
            periodSeconds: 5          
            failureThreshold: 3 

