apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-flask
  template:
    metadata:
      labels:
        app: sample-flask
    spec:
      containers:
        - name: sample-flask
          image: yashwanth0422/sample-flask:a0ac902182c3734c8423984d5d2f92b169b93100
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000

