name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Apply Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gitops-repo
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > ~/.kube/config

      - name: Apply manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
