name: GitOps Deployment

on:
  repository_dispatch:
    types: [update-deployment]

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print received payload
        run: |
          echo "Triggered by repository_dispatch"
          echo "Image tag: ${{ github.event.client_payload.image_tag }}"
