name: GitOps Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true

jobs:
  update-deployment:
    name: Update Deployment Manifest
    runs-on: ubuntu-latest

    steps:
      # Checkout the gitops repo itself
      - name: Checkout gitops-repo
        uses: actions/checkout@v3

      # Update deployment.yaml with the new image tag
      - name: Update Deployment Manifest
