name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gitops-repo
        uses: actions/checkout@v3

      - name: Update manifests with image tag
        env:
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          sed -i "s|image: .*|image: docker.io/${DOCKER_USERNAME}/sample-webapp:${IMAGE_TAG}|g" deployment.yaml
          git config user.email "ci@example.com"
          git config user.name "CI Bot"
          git add deployment.yaml
          git commit -m "Deploy image tag ${IMAGE_TAG}" || echo "No changes to commit"
          git push origin main
